const properties = [
  {
    id: 11,
    property_manager_id: 3,
    name: "HelloWorld1",
    address: "3116 Brando Gateway",
    unit: "APT 4604",
    city: "Toronto",
    province: "Ontario",
    postal_code: "56465",
    property_type: "Condominium",
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 12,
    property_manager_id: 3,
    name: "HelloWorld2",
    address: "536 Amanda Loaf",
    unit: "APT 5214",
    city: "Toronto",
    province: "Ontario",
    postal_code: "93432",
    property_type: "Condominium",
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 13,
    property_manager_id: 3,
    name: "HelloWorld3",
    address: "223 HelloWorld",
    unit: "APT 5214",
    city: "Toronto",
    province: "Ontario",
    postal_code: "93432",
    property_type: "Condominium",
    image_path: "http://placeimg.com/640/480/business",
  },
];

const allTickets = [
  {
    id: 1,
    property_id: 11,
    creator_id: 4,
    employee_id: 11,
    maintenance_type_id: 1,
    ticket_status_id: 1,
    description:
      "Ticket1 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
    estimated_cost: 411,
    actual_cost: 41,
    created_at: "2018-03-10T19:10:17.627Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 2,
    property_id: 11,
    creator_id: 6,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 1,
    description:
      "Ticket2 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
    estimated_cost: 809,
    actual_cost: null,
    created_at: "2019-01-30T08:53:12.963Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 3,
    property_id: 11,
    creator_id: 4,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 1,
    description:
      "Ticket3 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
    estimated_cost: 411,
    actual_cost: 41,
    created_at: "2018-03-10T19:10:17.627Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 4,
    property_id: 11,
    creator_id: 6,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 1,
    description:
      "Ticket4 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
    estimated_cost: 809,
    actual_cost: null,
    created_at: "2019-01-30T08:53:12.963Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 5,
    property_id: 11,
    creator_id: 4,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 2,
    description:
      "Ticket5 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
    estimated_cost: 411,
    actual_cost: 41,
    created_at: "2018-03-10T19:10:17.627Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 6,
    property_id: 11,
    creator_id: 4,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 2,
    description:
      "Ticket6 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
    estimated_cost: 411,
    actual_cost: 41,
    created_at: "2018-03-10T19:10:17.627Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 7,
    property_id: 11,
    creator_id: 6,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 2,
    description:
      "Ticket7 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
    estimated_cost: 809,
    actual_cost: null,
    created_at: "2019-01-30T08:53:12.963Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 8,
    property_id: 11,
    creator_id: 4,
    employee_id: null,
    maintenance_type_id: 1,
    ticket_status_id: 2,
    description:
      "Ticket8 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
    estimated_cost: 411,
    actual_cost: 41,
    created_at: "2018-03-10T19:10:17.627Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 9,
    property_id: 12,
    creator_id: 5,
    employee_id: 14,
    maintenance_type_id: 2,
    ticket_status_id: 1,
    description:
      "Ticket9 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
    estimated_cost: 761,
    actual_cost: null,
    created_at: "2018-12-22T04:35:53.442Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 10,
    property_id: 12,
    creator_id: 6,
    employee_id: 12,
    maintenance_type_id: 1,
    ticket_status_id: 2,
    description:
      "Ticket10 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
    estimated_cost: 809,
    actual_cost: null,
    created_at: "2019-01-30T08:53:12.963Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 11,
    property_id: 12,
    creator_id: 5,
    employee_id: 14,
    maintenance_type_id: 2,
    ticket_status_id: 1,
    description:
      "Ticket11----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
    estimated_cost: 761,
    actual_cost: null,
    created_at: "2018-12-22T04:35:53.442Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 12,
    property_id: 11,
    creator_id: 4,
    employee_id: 11,
    maintenance_type_id: 1,
    ticket_status_id: 3,
    description:
      "Ticket12 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
    estimated_cost: 411,
    actual_cost: 41,
    created_at: "2018-03-10T19:10:17.627Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 13,
    property_id: 11,
    creator_id: 6,
    employee_id: 12,
    maintenance_type_id: 1,
    ticket_status_id: 3,
    description:
      "Ticket13 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
    estimated_cost: 809,
    actual_cost: 968,
    created_at: "2019-01-30T08:53:12.963Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 14,
    property_id: 12,
    creator_id: 5,
    employee_id: 14,
    maintenance_type_id: 2,
    ticket_status_id: 3,
    description:
      "Ticket14 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
    estimated_cost: 761,
    actual_cost: 618,
    created_at: "2018-12-22T04:35:53.442Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 15,
    property_id: 12,
    creator_id: 6,
    employee_id: 12,
    maintenance_type_id: 1,
    ticket_status_id: 3,
    description:
      "Ticket15 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
    estimated_cost: 809,
    actual_cost: 968,
    created_at: "2019-01-30T08:53:12.963Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
  {
    id: 16,
    property_id: 12,
    creator_id: 5,
    employee_id: 14,
    maintenance_type_id: 2,
    ticket_status_id: 3,
    description:
      "Ticket16 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
    estimated_cost: 761,
    actual_cost: 618,
    created_at: "2018-12-22T04:35:53.442Z",
    completed_at: null,
    image_path: "http://placeimg.com/640/480/business",
  },
];

const ticketsOrganizedByPropertyId = [
  {
    property_id: 0,
    ticketsArray: [
      {
        id: 1,
        property_id: 11,
        creator_id: 4,
        employee_id: 11,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket1 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 2,
        property_id: 11,
        creator_id: 6,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket2 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 3,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket3 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 4,
        property_id: 11,
        creator_id: 6,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket4 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 5,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket5 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 6,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket6 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 7,
        property_id: 11,
        creator_id: 6,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket7 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 8,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket8 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 9,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 1,
        description:
          "Ticket9 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: null,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 10,
        property_id: 12,
        creator_id: 6,
        employee_id: 12,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket10 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 11,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 1,
        description:
          "Ticket11----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: null,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 12,
        property_id: 11,
        creator_id: 4,
        employee_id: 11,
        maintenance_type_id: 1,
        ticket_status_id: 3,
        description:
          "Ticket12 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 13,
        property_id: 11,
        creator_id: 6,
        employee_id: 12,
        maintenance_type_id: 1,
        ticket_status_id: 3,
        description:
          "Ticket13 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: 968,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 14,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 3,
        description:
          "Ticket14 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: 618,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 15,
        property_id: 12,
        creator_id: 6,
        employee_id: 12,
        maintenance_type_id: 1,
        ticket_status_id: 3,
        description:
          "Ticket15 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: 968,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 16,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 3,
        description:
          "Ticket16 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: 618,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
    ],
    statsForProperty: { totalUnsolved: 11, in_Progress: 5, pending: 6 },
  },
  {
    property_id: 11,
    ticketsArray: [
      {
        id: 1,
        property_id: 11,
        creator_id: 4,
        employee_id: 11,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket1 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 2,
        property_id: 11,
        creator_id: 6,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket2 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 3,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket3 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 4,
        property_id: 11,
        creator_id: 6,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 1,
        description:
          "Ticket4 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 5,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket5 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 6,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket6 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 7,
        property_id: 11,
        creator_id: 6,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket7 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 8,
        property_id: 11,
        creator_id: 4,
        employee_id: null,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket8 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 12,
        property_id: 11,
        creator_id: 4,
        employee_id: 11,
        maintenance_type_id: 1,
        ticket_status_id: 3,
        description:
          "Ticket12 ------ nisi veniam ad aperiam placeat officia doloribus. Animi alias voluptatem omnis sit. Deserunt qui aut. Qui ab magni veritatis similique voluptatibus. Tempore quidem nihil repudiandae saepe laborum quia molestias. Expedita a impedit nobis aut est.",
        estimated_cost: 411,
        actual_cost: 41,
        created_at: "2018-03-10T19:10:17.627Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 13,
        property_id: 11,
        creator_id: 6,
        employee_id: 12,
        maintenance_type_id: 1,
        ticket_status_id: 3,
        description:
          "Ticket13 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: 968,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
    ],
    statsForProperty: { totalUnsolved: 8, in_Progress: 4, pending: 4 },
  },
  {
    property_id: 12,
    ticketsArray: [
      {
        id: 9,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 1,
        description:
          "Ticket9 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: null,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 10,
        property_id: 12,
        creator_id: 6,
        employee_id: 12,
        maintenance_type_id: 1,
        ticket_status_id: 2,
        description:
          "Ticket10 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: null,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 11,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 1,
        description:
          "Ticket11----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: null,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 14,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 3,
        description:
          "Ticket14 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: 618,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 15,
        property_id: 12,
        creator_id: 6,
        employee_id: 12,
        maintenance_type_id: 1,
        ticket_status_id: 3,
        description:
          "Ticket15 ----- doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
        estimated_cost: 809,
        actual_cost: 968,
        created_at: "2019-01-30T08:53:12.963Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
      {
        id: 16,
        property_id: 12,
        creator_id: 5,
        employee_id: 14,
        maintenance_type_id: 2,
        ticket_status_id: 3,
        description:
          "Ticket16 ----- ratione dolorem. Nam voluptatibus blanditiis accusamus aliquam qui hic. Beatae quidem ut praesentium ab est dicta. Quas rerum earum facilis. Ea non asperiores fugiat enim consequatur ipsum.",
        estimated_cost: 761,
        actual_cost: 618,
        created_at: "2018-12-22T04:35:53.442Z",
        completed_at: null,
        image_path: "http://placeimg.com/640/480/business",
      },
    ],
    statsForProperty: { totalUnsolved: 3, in_Progress: 1, pending: 2 },
  },
  {
    property_id: 13,
    ticketsArray: [],
    statsForProperty: { totalUnsolved: 0, in_Progress: 0, pending: 0 },
  },
];

let numProperties = properties.length; // 3
let totalCostPlumbing = 0;
let totalCostELectrical = 0;
let totalCostGeneral = 0;
let final = [];
//  ["Property Name", "Plumbing", "Electrical", "General Maintenance"]
// ["Bridlewood", 1400, 3000, 1200]
console.log(numProperties);

let propArray = []

for (const num of properties) {
  final.push([]);
}

for (let i = 0; i < numProperties; i++) {
  final[i].push(properties[i].name);
}

for (let i = 1; i < numProperties + 1; i++) {
  // accesses ticketsArray in each property
  //    ticketsOrganizedByPropertyId[i].ticketsArray[0]

  for (let i = 1; i < numProperties + 1; i++) {
    propArray.push([])
  }

  //array of tickets for each prop
  // propArray[i].push(ticketsOrganizedByPropertyId[i].ticketsArray);
  // final[i-1].push(propArray[i])
}
// to get the costs
// ticketsOrganizedByPropertyId[].ticketsArray[loop through array put i here].actual_cost

// console.log('Test ', ticketsOrganizedByPropertyId[1].ticketsArray[0].actual_cost)
// console.log(propArray);



console.log(final);

// AllPropertiesComparisonGraph(ticketsOrganizedByPropertyId);

// module.exports = { AllPropertiesComparisonGraph };
