// const tickets = [
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 3,
//     employee_id: 12,
//     maintenance_type_id: 1,
//     ticket_status_id: 1,
//     description:
//       "Minima ipsum repellat culpa. Molestias dolorem aut cumque expedita non minus ipsam vel. Cum velit placeat molestiae ut autem similique voluptates minus.",
//     estimated_cost: 852,
//     actual_cost: 745,
//     created_at: "2020-02-02T09:31:57.074Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 5,
//     employee_id: 12,
//     maintenance_type_id: 2,
//     ticket_status_id: 2,
//     description:
//       "Eos similique similique. Sit rerum doloribus esse temporibus reprehenderit voluptatum similique et. Perspiciatis sint rerum eum nisi dolorum qui tempora facilis id. Illo dolorum facilis maiores consectetur similique.",
//     estimated_cost: 733,
//     actual_cost: 583,
//     created_at: "2018-09-15T22:32:22.877Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 3,
//     employee_id: 9,
//     maintenance_type_id: 1,
//     ticket_status_id: 2,
//     description:
//       "Explicabo voluptatem deleniti incidunt et consequatur eius at ipsum sunt. Id labore facilis eos et aliquid ut minus totam omnis. Omnis iusto provident corrupti eius enim. Nemo molestias ipsum libero dolorum et est itaque dolorum.",
//     estimated_cost: 61,
//     actual_cost: 856,
//     created_at: "2017-10-28T03:31:16.114Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 3,
//     employee_id: 12,
//     maintenance_type_id: 3,
//     ticket_status_id: 1,
//     description:
//       "Qui expedita aliquid cupiditate. Quam qui voluptate odit ipsam voluptatem voluptatem provident expedita. Quaerat maxime laborum natus.",
//     estimated_cost: 971,
//     actual_cost: 430,
//     created_at: "2018-06-06T21:35:21.382Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 5,
//     employee_id: 10,
//     maintenance_type_id: 2,
//     ticket_status_id: 2,
//     description:
//       "Cum ad consequuntur qui. Dolorem doloribus quia. Explicabo ipsam omnis enim voluptas. Dolor soluta corporis explicabo voluptas. Nam illo officia sit doloremque aspernatur beatae fugiat corrupti. Nam assumenda alias perspiciatis quam ea voluptates voluptas aut aut.",
//     estimated_cost: 307,
//     actual_cost: 776,
//     created_at: "2017-02-02T00:04:21.408Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 5,
//     employee_id: 8,
//     maintenance_type_id: 2,
//     ticket_status_id: 2,
//     description:
//       "Quibusdam sed eos dolorum unde. Maiores voluptatum quod voluptatum quia ea iste aut quia. Eum ut omnis quia repellendus impedit nostrum. Necessitatibus similique voluptatem delectus aut libero tempora.",
//     estimated_cost: 672,
//     actual_cost: 12,
//     created_at: "2020-01-08T12:22:49.778Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 5,
//     employee_id: 14,
//     maintenance_type_id: 2,
//     ticket_status_id: 1,
//     description:
//       "Eos velit fuga. Necessitatibus aspernatur quos ut porro ut ea quisquam. Provident sequi distinctio est sint in. Nobis quas consequuntur tempore. Illum earum consectetur. Nam dolores autem beatae iure.",
//     estimated_cost: 41,
//     actual_cost: 692,
//     created_at: "2018-10-15T08:12:31.444Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 7,
//     employee_id: 8,
//     maintenance_type_id: 2,
//     ticket_status_id: 2,
//     description:
//       "Minus quo corrupti dolorem et temporibus fugit ipsum sit est. Est provident iure doloremque omnis autem illo dolorum tenetur. Occaecati rerum eveniet laudantium dolores qui explicabo natus qui nostrum. Neque fuga et dolorem.",
//     estimated_cost: 935,
//     actual_cost: 185,
//     created_at: "2019-09-20T10:01:13.591Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 5,
//     employee_id: 10,
//     maintenance_type_id: 1,
//     ticket_status_id: 1,
//     description:
//       "Aut ut commodi quia quidem. Ut error earum perspiciatis commodi qui et. Molestiae est numquam magnam et soluta nemo.",
//     estimated_cost: 776,
//     actual_cost: 300,
//     created_at: "2018-03-08T17:06:09.415Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 6,
//     employee_id: 14,
//     maintenance_type_id: 1,
//     ticket_status_id: 1,
//     description:
//       "Incidunt ab sunt facilis aut eum in vel est. Blanditiis voluptas minima tenetur ducimus quidem est occaecati totam est. Neque et eligendi et odio facere deleniti. Et quibusdam ut facere quibusdam repellendus et. Qui nostrum et doloremque eligendi reprehenderit et voluptate et.",
//     estimated_cost: 434,
//     actual_cost: 23,
//     created_at: "2019-06-20T01:03:48.010Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 6,
//     employee_id: 12,
//     maintenance_type_id: 3,
//     ticket_status_id: 2,
//     description:
//       "Optio dolores itaque corporis in neque dolorem. Ad est error dolorem fugit quos cupiditate dignissimos eaque. Expedita nihil sunt rerum consequatur doloribus quo fugit et architecto. Est corrupti qui vel quas illo maiores. Pariatur totam quis quia quasi inventore magni omnis quidem repellendus.",
//     estimated_cost: 177,
//     actual_cost: 518,
//     created_at: "2019-10-30T22:07:37.473Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 4,
//     employee_id: 12,
//     maintenance_type_id: 3,
//     ticket_status_id: 1,
//     description:
//       "Aut vitae minus sequi aut illum ex officia rerum. Qui veritatis commodi fuga earum. Consequatur enim tempora voluptatum. Atque adipisci placeat sunt adipisci doloribus officiis qui sint. Est officia nihil suscipit quo sit quis sint.",
//     estimated_cost: 265,
//     actual_cost: 370,
//     created_at: "2018-05-28T06:10:43.291Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 3,
//     employee_id: 13,
//     maintenance_type_id: 1,
//     ticket_status_id: 2,
//     description:
//       "Aspernatur neque perspiciatis minima alias voluptates dolore. Ipsam eaque odit. Tenetur sit id aperiam eos asperiores ipsam aliquid voluptate. Quae soluta deleniti.",
//     estimated_cost: 163,
//     actual_cost: 728,
//     created_at: "2017-03-10T08:35:08.732Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 3,
//     employee_id: 11,
//     maintenance_type_id: 2,
//     ticket_status_id: 1,
//     description:
//       "Rerum labore quia est ullam non qui sed laboriosam. Libero ut esse reiciendis enim occaecati accusantium. Aliquam veritatis veritatis nobis architecto aut. Commodi temporibus qui debitis ut sit architecto. Non quia nam culpa vel veritatis omnis voluptas et. Debitis reiciendis dolores velit eaque veritatis.",
//     estimated_cost: 460,
//     actual_cost: 368,
//     created_at: "2018-01-28T00:13:32.481Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 6,
//     employee_id: 10,
//     maintenance_type_id: 2,
//     ticket_status_id: 1,
//     description:
//       "Temporibus ut qui quod ipsa voluptas possimus quis quidem aspernatur. Aut assumenda iste doloremque eveniet et optio impedit amet. Laboriosam non illum sint quis. Dolorem praesentium aliquid ut voluptate iure aliquid. Aperiam ea aliquam id.",
//     estimated_cost: 132,
//     actual_cost: 277,
//     created_at: "2019-12-08T09:02:01.653Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
//   {
//     id: 1,
//     property_id: 1,
//     creator_id: 6,
//     employee_id: 12,
//     maintenance_type_id: 1,
//     ticket_status_id: 2,
//     description:
//       "Nihil doloremque esse delectus. Adipisci consequuntur eius enim vero aperiam. Dolorum et debitis odio libero eum quisquam et ut a.",
//     estimated_cost: 809,
//     actual_cost: 968,
//     created_at: "2019-01-30T08:53:12.963Z",
//     completed_at: null,
//     image_path: "http://placeimg.com/640/480/business",
//     property_manager_id: 1,
//     name: "Yessenia Common",
//     address: "797 Marques Island",
//     unit: "APT 3327",
//     city: "Toronto",
//     province: "Ontario",
//     postal_code: "07717-0821",
//     property_type: "Condominium",
//   },
// ];

const maintenanceCountPieChart = function(tickets) {

  // let plumbingList = [];
  // let electricalList = [];
  // let generalList = [];


  let numPlumbing = 0;
  let numElectrical = 0;
  let numGeneral = 0;

  for (let i = 0; i < tickets.length; i++) {
    if (tickets[i].maintenance_type_id === 1 && tickets[i].ticket_status_id === 3) {
      numPlumbing += 1;
    } else if (tickets[i].maintenance_type_id === 2  && tickets[i].ticket_status_id === 3) {
      numElectrical += 1
    } else if (tickets[i].maintenance_type_id ===3  && tickets[i].ticket_status_id === 3) {
      numGeneral += 1
    }
  }

  let finalCount = {
    numPlumbing,
    numElectrical,
    numGeneral
  }

  return finalCount;
};

module.exports = { maintenanceCountPieChart }